/*
 * bit-test-results-exporter
 *
 * This protocol defines the API for **test-results-exporter** service in the **BIT** functionality.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	sw2 "./internal/bit-indexer"
	sw1 "./internal/bit-test-results-exporter"
	"log"
	"net/http"
)

func main() {

	//logger := log.New(os.Stdout, "api ", log.LstdFlags|log.Lshortfile)
	//
	//router := sw.NewRouter()
	//
	//srv := server.NewServer(router, ":8080")

	log.Printf("Server started")

	router := sw1.NewRouter()
	router2 := sw2.NewRouter()

	go func() {
		err := http.ListenAndServe(":8080", router)
		if err != nil {
			log.Fatalln(err)
		}
	}()
	log.Printf("Server 8080 started")
	err := http.ListenAndServe(":8081", router2)
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("Server 8081 started")
	//http.ListenAndServe("8081", router)
}
