/*
 * bit-test-results-exporter
 *
 * This protocol defines the API for **test-results-exporter** service in the **BIT** functionality.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	sw "./internal/bit-test-results-exporter"
	"log"
	"net/http"
)

func main() {

	//logger := log.New(os.Stdout, "api ", log.LstdFlags|log.Lshortfile)
	//
	//router := sw.NewRouter()
	//
	//srv := server.NewServer(router, ":8080")

	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
