---
version: "1.0.1"
host: "localhost"
api_version: "1.0.1"
bit_config_port: ":8084"
bit_handler_port: ":8086"
bit_history_curator_port: ":8083"
bit_indexer_port: ":8081"
bit_query_port: ":8085"
bit_storage_port: ":8082"
bit_exporter_port: ":8087"
bit_config_service_path: "./internal/bitConfig"
bit_exporter_service_path: "./internal/bitTestResultsExporter"
bit_handler_service_path: "./internal/bitHandler"
bit_indexer_service_path: "./internal/bitIndexer"
bit_query_service_path: "./internal/bitQuery"
bit_history_curator_service_path: "./internal/bitHistoryCurator"
bit_storage_service_path: "./internal/bitStorageAccess"
storage_write_url: "http://localhost:8082/data/write"
storage_read_url: "http://localhost:8082/data/read"
storage_delete_url: "http://localhost:8082/data/delete"
config_failures_path: "./configs/config_failures/"
config_user_group_path: "./configs/config_user_groups_filtering/"
exporter_default_bw_size: 20
exporter_default_bw_units: "KiB"
indexer_url: "http://localhost:8081/report/raw"
exporter_url: "http://localhost:8087/report/raw"
handler_trigger_period: 1
handler_trigger_type: "CBIT"
bit_history_curator_aged_data_limit: "72h"
ssh_key: "C:/Users/Eden/Documents/bit-framework/configs/prog_configs/sshConfigs/localhost.key"
ssh_cert: "C:/Users/Eden/Documents/bit-framework/configs/prog_configs/sshConfigs/localhost.crt"
ssh_csr: "C:/Users/Eden/Documents/bit-framework/configs/prog_configs/sshConfigs/localhost.csr"
use_https: false