/*
 * bit-test-results-exporter
 *
 * This protocol defines the API for **test-results-exporter** service in the **BIT** functionality.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Bandwidth struct {
	// Upper limit value, 0 or negative means unlimited
	Size float32 `json:"size,omitempty" validate:"required"`
	// KiB/MiB/GiB/TiB/K/M/G/T, 1_KiB = 1024, 1_K = 1000
	UnitsPerSecond string `json:"unitsPerSecond,omitempty" validate:"required"`
}
