/*
 * bit-storage-access
 *
 * This protocol defines the API for **storage-access** service in the **BIT** functionality.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type StorageExtendedStatus struct {
	// The type of the concrete used storage
	StorageType string `json:"storageType"`
	// The concrete DB used as storage. Relevant only if storageType='data_base'
	DataBase string `json:"dataBase,omitempty"`
}
