/*
 * bit-storage-access
 *
 * This protocol defines the API for **storage-access** service in the **BIT** functionality.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bitStorageAccess

import (
	. "../models"
	"encoding/json"
	"log"
	"net/http"
	"time"
)

func GetExtendedStatus(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	response := StorageExtendedStatus{StorageType: "file_system"}
	err := json.NewEncoder(w).Encode(&response)
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		log.Fatalln(err)
	}
	w.WriteHeader(http.StatusOK)
}

func StorageGetPing(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	response := PongBody{Timestamp: time.Now(), Version: "1/00", Host: "EdenNadav", Ready: true, ApiVersion: "alpha"}
	err := json.NewEncoder(w).Encode(&response)
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		log.Fatalln(err)
	}
	w.WriteHeader(http.StatusOK)
}
